// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL73gZpUTjGHWWmuB5SM73jWlNhWllOfM',
    appId: '1:361326435107:web:078237f2e9a1d81f7b4a96',
    messagingSenderId: '361326435107',
    projectId: 'spixah-5254d',
    authDomain: 'spixah-5254d.firebaseapp.com',
    storageBucket: 'spixah-5254d.firebasestorage.app',
    measurementId: 'G-MGXKTZQQLD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_mbodvNBe5vBAxI51-Gk8lTucsPBfq-g',
    appId: '1:361326435107:android:83e81a266a5ffb637b4a96',
    messagingSenderId: '361326435107',
    projectId: 'spixah-5254d',
    storageBucket: 'spixah-5254d.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAL73gZpUTjGHWWmuB5SM73jWlNhWllOfM',
    appId: '1:361326435107:web:2cd0a53e466d48307b4a96',
    messagingSenderId: '361326435107',
    projectId: 'spixah-5254d',
    authDomain: 'spixah-5254d.firebaseapp.com',
    storageBucket: 'spixah-5254d.firebasestorage.app',
    measurementId: 'G-X3P77NY80Q',
  );
}
